### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Rogero0o** [frakbot/JumpingBeans#1]
Error:(37, 0) Cause: assert localProps['keystore.props.file']
       |         |
       |         null
       [sdk.dir:F:\adt-bundle-windows-x86_64_with_Android_5.0\sdk]

how can i fix it ? waiting for you answer , thanks

**Comment by frapontillo** [comment]
You're probably attempting to sign the package via gradle: don't do that, the keystore is only used to push packages to Maven.
