### ISSUE TITLE
Displaying in different types of screen

### ISSUE THREAD

**Issue by ghost** [frakbot/JumpingBeans#10]
Here png how it looks on lcd.
![2](https://cloud.githubusercontent.com/assets/9719496/12393446/b4955640-be06-11e5-8413-aa7cce3aad99.png)

Here png how it looks on ink.
![default](https://cloud.githubusercontent.com/assets/9719496/12393188/37f42612-be05-11e5-8497-ee09f8eaf496.png)

How to make invisible edging characters ink?

**Comment by frapontillo** [comment]
![](http://i.giphy.com/dBPe9WlOAiTuM.gif)

**Comment by rock3r** [comment]
![spock-joke](https://cloud.githubusercontent.com/assets/153802/12394247/9001b530-bdf2-11e5-9543-deb355a8b84d.gif)
