### ISSUE TITLE
Create a JumpingBeans by using its Builder

### ISSUE THREAD

**Issue by Zyf21** [frakbot/JumpingBeans#11]
Sorry I'm very stupid. How can I create  а JumpingBeans by using its Builder? I do not know how to do that.

**Comment by rock3r** [comment]
Just look at the sample, mate https://github.com/frakbot/JumpingBeans/blob/master/app/src/main/java/net/frakbot/jumpingbeans/demo/MainActivity.java#L50-L54

**Comment by Zyf21** [comment]
Thank you very much.I just started using github and I do not know where everything is here.
