### ISSUE TITLE
Doesn't work when textAllCaps="true"

### ISSUE THREAD

**Issue by pardom-zz** [frakbot/JumpingBeans#7]
If this can't be worked around, a note should be made that `android:textAllCaps` must be `false`.

**Comment by rock3r** [comment]
`textAllCaps` is fundamentally broken as it strips all spans away. You should not use it. That said, yeah. It won't work with it. But it's hardly JumpingBeans's fault...

**Comment by pardom-zz** [comment]
I didn't intent to blame JumpingBeans. I just think you should make a note about not using `textAllCaps`.
