### ISSUE TITLE
Short animated duty cycle causes animation repeat

### ISSUE THREAD

**Issue by pardom-zz** [frakbot/JumpingBeans#8]
I'm seeing some repeats in animation when I set the animated duty cycle to `<= 0.5`. And I think this is due to using `Math.max()` to limit the interpolated value. When the animation range is small enough, the time is interpolated to fit more than one sine wave.

According to the method doc ("Sets the fraction of the animation loop time spent actually animating. The rest of the time will be spent "resting"), it seems that this:

``` java
double radians = (input / animRange) * Math.PI;
double interpolatedValue = Math.max(0f, Math.sin(radians));
return (float) interpolatedValue;
```

Should actually be this:

``` java
if (input > animRange) return;
double radians = (input / animRange) * Math.PI;
double interpolatedValue = Math.sin(radians);
return (float) interpolatedValue;
```

Thoughts?

**Comment by rock3r** [comment]
That would work, if you wanted to change the behaviour of the animation. I suppose the documentation might be a bit misleading given what the code actually does... Will issue a minor update to address this.
